import sqlite3 as sq3
import random as rd

## Indian Bank Database Management System

#creating the database and is executed only once via runing this file
#it creates a database file named bankdatabase.db in the Indian Bank folder
def create_database():
    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur = con.cursor()

        cur.execute('''CREATE TABLE IF NOT EXISTS bankaccounts(
                    
                    name TEXT NOT NULL,
                    fname TEXT NOT NULL,
                    dob TEXT NOT NULL,
                    balance REAL NOT NULL,
                    password TEXT NOT NULL
                    )''')
        con.commit()

#this creates a new bank account and returns autogenerated password

def create_account(name, fname, dob, balance,password):
    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur = con.cursor()

        
        cur.execute('''INSERT INTO bankaccounts VALUES (?,?,?,?,?)''',
                    (name, fname, dob, balance, password))

        con.commit()

#this allows you to login to your account
#it returns the rowid and all the values of the account if successful, else returns False

def login(name:str,password:str):
    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur=con.cursor()
        cur.execute('''SELECT rowid,* FROM bankaccounts WHERE name=? AND password=?''',(name,password))
        value=cur.fetchall()
        if value:
            return value
        else:
            return False
    
def updating_database(rowid:int,placevalue: str,value):
    valid_columns=['name','fname','dob','balance','password']
    if placevalue not in valid_columns:
        raise ValueError(f"{placevalue}is not a valid column name.")

    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur = con.cursor()
        #using string formatting to create the SQL query dynamically
        #placevalue is the column name to be updated
        sql=f'''UPDATE bankaccounts SET {placevalue}=? WHERE rowid=?'''
        cur.execute(sql, (value, rowid))
        con.commit()

def deposite(rowid:int,amount: float):
    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur = con.cursor()
        cur.execute('''UPDATE bankaccounts SET balance=balance+? WHERE rowid=?''', (amount, rowid))
        con.commit()


def remove_account(rowid:int):
    with sq3.connect('./Indian Bank/bankdatabase.db') as con:
        cur = con.cursor()
        cur.execute('''DELETE FROM bankaccounts WHERE rowid=?''', (rowid,))
        con.commit()
        

#this allows you to change your password   
    
def change_password(rowid:int,npassword: str):
    updating_database(rowid, 'password', npassword)
    return None

    






    
    



if __name__ == "__main__":
    create_database()
